import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "../Provider";
import SideMenuBar from "./components/SideMenuBar";
import AppBar from "./components/AppBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen w-full`}>
        <Providers>
          <AppBar />
          <div className="w-full min-h-screen flex gap-3">
            <SideMenuBar />
            <div className="shadow-[0.1px_0.1px_5px_0.1px_black] mx-2 flex justify-center rounded-lg w-full">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
